apiVersion: build.knative.dev/v1alpha1
kind: BuildTemplate
metadata:
  name: kaniko
spec:
  parameters:
  - name: IMAGE
    description: The name of the image to push
  - name: DOCKERFILE
    description: Path to the Dockerfile to build.
    default: /workspace/Dockerfile

  steps:
  - name: debug
    image: gcr.io/kaniko-project/executor:debug@sha256:5a8d578dc7ff0114daadb20902bf8529f9a2257440d68ac9c6c4b7da98665ca1
    command:
    - /busybox/sh
    - -ce
    - >
      PARAM_DOCKERFILE=${DOCKERFILE};
      PARAM_IMAGE=${IMAGE};

      mkdir /workspace/selfcheck1;
      echo "FROM alpine:3.8" > /workspace/selfcheck1/Dockerfile;
      echo "RUN date > /build-date.txt" >> /workspace/selfcheck1/Dockerfile;
      /kaniko/executor -c /workspace/selfcheck1 --no-push;
      /kaniko/executor -c /workspace/selfcheck1 -d v2.registry.svc.cluster.local:5000/knative-test/selfcheck1 --insecure;
  - name: check-registry-access
    image: solsson/curl@sha256:523319afd39573746e8f5a7c98d4a6cd4b8cbec18b41eb30c8baa13ede120ce3
    args:
    - -v
    - http://v2.registry.svc.cluster.local:5000/v2/
    - -f
    - --retry
    -   "5"
    - --retry-connrefused
  - name: build-and-push
    image: gcr.io/kaniko-project/executor@sha256:413fe14232a5f37f02a57758fe891993df3d58114ed948b00c9b044ed2f05f45
    args:
    - --dockerfile=${DOCKERFILE}
    - --destination=${IMAGE}
    - --insecure
    - --verbosity=info
